org: mtharrison
app: thought-coach-openai-api
service: thought-coach-openai-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  websocketsApiRouteSelectionExpression: '$request.body.route'

functions:
  connectHandler:
    timeout: 180
    handler: functions.connect
    events:
      - websocket: $connect
      - websocket: $disconnect
  completion:
    timeout: 180
    handler: functions.completion
    environment:
      OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    events:
      - websocket:
          route: completion
          routeResponseSelectionExpression: $default

useDotenv: true

custom:
  webpack:
    includeModules:
      packagePath: './package.json'
  serverless-offline:
    websocketPort: 3001
plugins:
  - serverless-offline
