import {
  Button,
  Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalBody,
  ModalFooter,
  Divider,
  Text,
} from '@chakra-ui/react';

export default function Disclaimer({
  disclaimerAccepted,
  setDisclaimerAccepted,
}: {
  disclaimerAccepted: boolean;
  setDisclaimerAccepted: Function;
}) {
  const onClose = () => setDisclaimerAccepted(true);

  return (
    <Modal
      closeOnEsc={false}
      closeOnOverlayClick={false}
      onClose={onClose}
      isOpen={!disclaimerAccepted}
      scrollBehavior={'inside'}
      size={{ sm: 'md', md: '3xl' }}
    >
      <ModalOverlay backdropFilter="blur(4px)" />
      <ModalContent bg="white">
        <ModalHeader bg="">DISCLAIMER</ModalHeader>
        <Divider></Divider>
        <ModalBody>
          <Text mt={3} fontWeight="bold">
            THIS APPLICATION DOES NOT PROVIDE MEDICAL ADVICE.
          </Text>
          <Text mt={4}>
            This research app is intended to explore the potential for using
            artificial intelligence in mental health therapy. It is not intended
            to replace professional medical advice, diagnosis, or treatment. The
            information provided by the app is for educational and research
            purposes only.
          </Text>
          <Text mt={4}>
            It uses artificial intelligence (AI) technology to provide its
            services and does not involve any human intervention. Please note
            that the app's responses and suggestions are generated by machine
            learning algorithms and are not based on human input. While the app
            strives to provide accurate and helpful information, its suggestions
            and advice may not always be perfect or applicable to every
            situation. It does not equate to a therapist-patient relationship.
            If you are experiencing a mental health emergency, please contact
            your local health provider immediately.{' '}
          </Text>
          <Text mt={4}>
            Any reliance you place on such information provided from this app is
            therefore strictly at your own risk. The creators of this app
            disclaim any liability for any damage or loss, including without
            limitation, indirect or consequential loss or damage, or any damage
            or loss whatsoever arising from the use of this app. By accepting
            this, you acknowledge that you have read and understood this legal
            disclaimer and agree to be bound by its terms and conditions.{' '}
          </Text>{' '}
        </ModalBody>
        <Divider mt={5}></Divider>
        <ModalFooter>
          <Button colorScheme="red" onClick={onClose}>
            Accept{' '}
          </Button>
        </ModalFooter>
      </ModalContent>
    </Modal>
  );
}
