service: thought-coach-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  connectHandler:
    timeout: 180
    handler: index.connect
    events:
      - websocket: $connect
      - websocket: $disconnect
  defaultHandler:
    timeout: 180
    handler: index.handler
    events:
      - websocket: $default

custom:
  webpack:
    includeModules:
      packagePath: './package.json'
